# include dracula.conf
# include gruvbox.conf
# include everforest.conf

# font_family	JetBrains Mono
font_family	FiraCode Nerd Font

# (mac) Use the option key as alt
macos_option_as_alt yes


# BEGIN_KITTY_THEME
# Catppuccin-Mocha
include catppuccin-mocha.conf
# END_KITTY_THEME
