# include dracula.conf
# include gruvbox.conf
# include everforest.conf

# font_family	JetBrains Mono
font_family	FiraCode Nerd Font



# BEGIN_KITTY_THEME
# Catppuccin-Mocha
include current-theme.conf
# END_KITTY_THEME
