set -g default-terminal "xterm-256color"
set -ga terminal-overrides ",xterm-256color:Tc"

# vi keybindings
setw -g mode-keys vi
set -g status-key vi

### Key remaps
bind -r k select-pane -U 
bind -r j select-pane -D 
bind -r h select-pane -L 
bind -r l select-pane -R

bind -r C-k resize-pane -U 5
bind -r C-j resize-pane -D 5
bind -r C-h resize-pane -L 5
bind -r C-l resize-pane -R 5

# allow the title bar to adapt to whatever host you connect to
set -g set-titles on
set -g set-titles-string "#T"

# List of plugins
set -g @plugin "tmux-plugins/tpm"
set -g @plugin "tmux-plugins/tmux-sensible"

# Initialize TMUX plugin manager
run "~/.tmux/plugins/tpm/tpm"

bind y set status


