# vi keybindings
setw -g mode-keys vi
set -g status-keys vi

# Enable mouse
set -g mouse on

# Standard tmux pane navigation (prefix + hjkl)
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Pane resizing (prefix + Ctrl+hjkl) with repeat
bind -r C-h resize-pane -L 3
bind -r C-j resize-pane -D 3
bind -r C-k resize-pane -U 3
bind -r C-l resize-pane -R 3

# Vim-style copy mode
bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi V send -X select-line
bind-key -T copy-mode-vi y send -X copy-pipe-and-cancel 'xclip -in -selection clipboard'

# Misc settings
set -g detach-on-destroy off
set -g status-position bottom
set-option -g repeat-time 500
set -g history-limit 30000

# Keep default prefix (Ctrl+B)
set-option -g prefix C-b

# Reload config
bind-key r source-file ~/.config/tmux/tmux.conf \; display-message "Config reloaded"

# Terminal settings
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*256col*:Tc"
set -ga terminal-overrides ",xterm-kitty:Tc"

# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'hendrikmi/tmux-cpu-mem-monitor'

# theme config
gray_light="#D8DEE9"
gray_medium="#abb2bf"
gray_dark="#3B4252"
green_soft="#A3BE8C"
blue_muted="#81A1C1"
cyan_soft="#88C0D0"

gb_grey_light="#514A43"
gb_grey_font="#978B76"
gb_yellow="#C49425"
gb_grey_dark="#3F3937"
gb_dark_brown="#282828"
gb_background="#302D2C"
gb_inactive_bg="#403A38"
gb_inactive_fg="#B6A98A"

set -g status-left-length 100
set -g status-style "bg=$gb_background,fg=$gray_light"

set -g status-left "#[fg=$gb_grey_font,bg=$gb_grey_light,bold]  #S #[fg=default,bg=default] "
set -g status-right "#(top -bn1 | grep 'Cpu(s)' | awk '{print $2}' | cut -d'%' -f1) #(free | grep Mem | awk '{printf \"%.1f%%\", $3/$2 * 100}') "

set -g window-status-current-format "#[bg=$gb_yellow,fg=$gb_background,bold] #I:#W "
set -g window-status-format "#[bg=$gb_inactive_bg,fg=$gb_inactive_fg] #I:#W "
set -g message-style "fg=$gray_light,bg=default"
set -g mode-style "fg=$gray_dark,bg=$blue_muted"
set -g pane-border-style "fg=$gray_dark"
set -g pane-active-border-style "fg=$gray_medium"
set -g pane-border-lines heavy


# Initialize plugin manager
run '~/.tmux/plugins/tpm/tpm'
